"""Game mechanics

Revision ID: 9578f07c42a9
Revises: e004e7f3f09f
Create Date: 2020-07-20 21:52:43.582984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9578f07c42a9'
down_revision = 'e004e7f3f09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('started', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'player', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_column('player', 'game_id')
    op.drop_column('game', 'started')
    # ### end Alembic commands ###
